name: Ubuntu

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v2

      - name: install GoogleTest
        if: ${{ steps.cache.output.cache-hit != 'true' }}
        run: |
          cd ..
          git clone https://github.com/google/googletest.git --branch v1.13.0
          cd googletest
          cmake -Bbuild -DCMAKE_INSTALL_PREFIX=/usr/local
          cmake --build build --config Release
          sudo cmake --build build --target install --config Release

      - name: Install OpenGL envs
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libglu1-mesa-dev mesa-common-dev
          sudo apt-get install -y libxmu-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev

      - name: Install GLFW3
        run: |
          sudo apt-get install -y libglfw3-dev

      - name: Install GLM
        run: |
          git clone https://github.com/g-truc/glm.git
          cd glm && git checkout 0.9.9.8
          sudo cp -R glm /usr/local/include

      - name: Install Eigen
        run: |
          sudo apt-get install -y libeigen3-dev

      - name: configure
        run: |
          mkdir build
          cd build
          cmake .. -Dnama_ENABLE_CODE_COVERAGE=1 -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: build
        run: |
          cd build
          make -j4
